name: Bodet News Robot

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install library
        run: |
          pip install google-generativeai edge-tts

      - name: Jalankan bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Upload hasil
        uses: actions/upload-artifact@v4
        with:
          name: bodet-news
          path: |
            naskah_berita.txt
            audio_berita.mp3
